---

- name: Trust mopidy developer GPG key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: Ensure mopidy repository is available
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://apt.mopidy.com/ buster main contrib non-free
    - deb-src https://apt.mopidy.com/ buster main contrib non-free

- name: Ensure mopidy is installed
  apt:
    name: mopidy
    state: present

- name: Install mopidy packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ mopidy_packages }}"
  notify: restart mopidy

- name: Install gstreamer plugin(s)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
