---

- block:
  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - autoconf
      - gcc
      - python-dev

  - name: Download pip
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /root/get-pip.py

  - name: Check if pip installed
    stat:
      path: "/usr/local/bin/pip"
    register: stat_result

  - name: Install recent pip
    shell: python get-pip.py
    args:
      chdir: /root
    when: stat_result.stat.exists == False
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version|int < 9) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 18)

- name: Install pip
  apt:
    name: python-pip
    state: present
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 9) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 18)

- name: Install external extensions
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ mopidy_pip }}"
  notify: restart mopidy
